export const MONGO_MODELS = {
    USER_MASTER: "USER_MASTER",
    ORGANISATION_MASTER: "ORGANISATION_MASTER",
    EMPLOYEE_TYPE_MASTER: "EMPLOYEE_TYPE_MASTER",
    DEPARTMENT_MASTER: "DEPARTMENT_MASTER",
    ROLE_MASTER: "ROLE_MASTER",
    ACCESS_MASTER: "ACCESS_MASTER",
    ADDRESS_MASTER: "ADDRESS_MASTER",
    DESIGNATION_MASTER: "DESIGNATION_MASTER",
    TEAM_MASTER: "TEAM_MASTER",
    TEAM_MEMBER_MASTER: "TEAM_MEMBER_MASTER",
    CONTINENT_MASTER: "CONTINENT_MASTER",
    REGION_MASTER: "REGION_MASTER",
    COUNTRY_MASTER: "COUNTRY_MASTER",
    STATE_MASTER: "STATE_MASTER",
    LOCATION_MASTER: "LOCATION_MASTER",
    WAREHOUSE_MASTER: "WAREHOUSE_MASTER",
    PRODUCT_CATEGORY_MASTER: "PRODUCT_CATEGORY_MASTER",
    PRODUCT_MASTER: "PRODUCT_MASTER",
    VENDOR_MASTER: "VENDOR_MASTER",
    PURCHASE_ORDER_MASTER: "PURCHASE_ORDER_MASTER",
    TRANSACTION_MASTER: "TRANSACTION_MASTER",
    CUSTOMER_MASTER: "CUSTOMER_MASTER",
    CUSTOMER_CONTACT_MASTER: "CUSTOMER_CONTACT_MASTER",
    CUSTOMER_TYPE_MASTER: "CUSTOMER_TYPE_MASTER",
    INDUSTRY_TYPE_MASTER: "INDUSTRY_TYPE_MASTER",
    BUILDING_TYPE_MASTER: "BUILDING_TYPE_MASTER",
    PROJECT_TYPE_MASTER: "PROJECT_TYPE_MASTER",
    PAINT_TYPE_MASTER: "PAINT_TYPE_MASTER",
    INCOTERM_MASTER: "INCOTERM_MASTER",
    CURRENCY_MASTER: "CURRENCY_MASTER",
    QUOTE_STATUS_MASTER: "QUOTE_STATUS_MASTER",
    APPROVAL_AUTHORITY_MASTER: "APPROVAL_AUTHORITY_MASTER"
  }as const;

export const SUCCESS = "Success";
export const FAILED = "Failed";
export const PENDING = "Pending";
export const COMPLETED = "Completed";
export const CANCELLED = "Cancelled";
export const REJECTED = "Rejected";
export const APPROVED = "Approved";
export const DRAFT = "Draft";
export const SUBMITTED = "Submitted";
export const ACTIVE = "Active";
export const INACTIVE = "Inactive";
export const BODY_REQUIRED = "Body is required";
export const INVALID_ID = "Invalid ID"; 
export const ERROR = "Error" 
export const INSUFFIENT_DATA = "Insufficient data" 
export const INVALID_REQUEST = " Invalid request"
export const INVALID_EMAIL = "Invalid email"

export const ROLES = {
    SUPER_ADMIN: "Super Admin",
    ADMIN: "Admin",
    USER: "User",
} as const;

export const PERMISSIONS = {
    CREATE: "Create",
    READ: "Read",
    UPDATE: "Update",
    DELETE: "Delete",
} as const;
