import mongoose from "mongoose";

export interface UserDocument {
    _id?: mongoose.ObjectId,
    empId: string,
    firstName: string,
    lastName: string,
    email: string,
    password: string,
    role: mongoose.ObjectId,
    fullName: string,
    shortName: string,
    designation: mongoose.ObjectId,
    employeeType: mongoose.ObjectId,
    department: mongoose.ObjectId,
    location: string,
    reportingTo: string,
    isActive: boolean,
    status: string,
    availability: string,
    extension: string,
    mobile: string,
    joiningDate: Date,
    relievingDate: Date,
    access:mongoose.ObjectId,
    addedBy: string,
    updatedBy: string,
    organisation: mongoose.ObjectId,
}