export interface UserDocument {
    _id?: string,
    empId: string,
    firstName: string,
    lastName: string,
    email: string,
    password: string,
    role: string,
    fullName: string,
    shortName: string,
    designation: string,
    employeeType: string,
    department: string,
    location: string,
    reportingTo: string,
    isActive: boolean,
    status: string,
    availability: string,
    extension: string,
    mobile: string,
    joiningDate: Date,
    relievingDate: Date,
    access:any,
    addedBy: string,
    updatedBy: string,
}