name: Deploy Next.js on Push to Master

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # This tells GitHub Actions to run on your on-premises Windows runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust this to your project’s required Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy Application
      run: |
        echo "Stopping current service (if necessary)..."
        REM Insert command to stop your running Next.js service, for example:
        REM taskkill /F /IM node.exe

        echo "Deploying new build..."
        REM Optionally, copy or replace build files as needed
        REM If your deployment consists of moving new files to a specific directory, include those commands here.

        echo "Restarting service..."
        REM Insert command to start your Next.js application. This might be a PM2 command, a Windows service start, or any custom script.
        REM For example, if using PM2:
        REM pm2 start npm --name "nextjs-app" -- start