name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes from master
        shell: bash
        run: |
          git pull origin master

      - name: Delete node_modules
        shell: bash
        run: |
          if [ -d "node_modules" ]; then
            rm -rf node_modules
          fi

      - name: Install dependencies
        run: npm install

      - name: Check if any Node.js process is running and kill it
        shell: cmd
        run: |
          for /f "tokens=2 delims=," %%i in ('tasklist /fi "imagename eq node.exe" /fo csv /nh') do (
            echo Node.js process is running with PID %%i. Killing it...
            taskkill /PID %%i /F
          ) || echo No running Node.js process found.

      - name: Build the application
        run: npm run build

      - name: Start the application
        run: npm run start
