name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set working directory
        shell: bash
        run: cd /e/AceroApplications  # Optional: GitHub Actions doesn't persist `cd`, use working-directory instead if needed

      - name: Pull latest changes from master
        shell: bash
        working-directory: /e/AceroApplications
        run: |
          chmod -R u+rw .git || true
          rm -f .git/index.lock || true
          git pull origin master

      - name: Delete node_modules
        shell: bash
        working-directory: /e/AceroApplications
        run: |
          rm -rf node_modules || echo "No node_modules to delete"

      - name: Install dependencies
        shell: bash
        working-directory: /e/AceroApplications
        run: npm install

      - name: Export environment variables
        shell: bash
        run: |
          set -a
          source /e/AceroApplications/.env
          set +a

      - name: Install PM2 globally (if not already installed)
        shell: bash
        run: |
          if ! command -v pm2 &> /dev/null; then
            echo "PM2 not found. Installing globally..."
            npm install -g pm2
          else
            echo "PM2 is already installed."
          fi

      - name: Stop existing PM2 app (if running)
        shell: bash
        run: |
          pm2 stop acero-app || echo "No running PM2 app to stop"
          pm2 delete acero-app || echo "No PM2 app to delete"

      - name: Build the application
        shell: bash
        working-directory: /e/AceroApplications
        run: |
          set -a
          source .env
          set +a
          npm run build

      - name: Start the application with PM2
        shell: bash
        working-directory: /e/AceroApplications
        run: |
          set -a
          source .env
          set +a
          pm2 start npm --name "acero-app" -- run start
          pm2 save

      - name: Show PM2 logs
        shell: bash
        run: |
          echo "Showing last 50 lines of PM2 logs for acero-app..."
          pm2 logs acero-app --lines 50
