name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes from master
        shell: bash
        working-directory: E:/AceroApplications
        run: git pull origin master

      - name: Delete node_modules
        shell: bash
        working-directory: E:/AceroApplications
        run: |
          if [ -d "node_modules" ]; then
            echo "Removing existing node_modules directory..."
            rm -rf node_modules
          else
            echo "No node_modules directory to delete."
          fi

      - name: Install dependencies
        shell: bash
        working-directory: E:/AceroApplications
        run: npm install

      - name: Load environment variables from .env file
        shell: bash
        working-directory: E:/AceroApplications
        run: |
          if [ -f ".env" ]; then
            echo "Loading .env file from E:/AceroApplications/.env..."
            export $(grep -v '^#' .env | xargs)
          else
            echo "No .env file found."
          fi

      - name: Check if any Node.js process is running and kill it
        shell: bash
        run: |
          echo "Looking for running node.exe processes..."
          NODE_PROCESSES=$(tasklist | grep "node.exe" || true)

          if [ -n "$NODE_PROCESSES" ]; then
            echo "Found Node.js process(es):"
            echo "$NODE_PROCESSES"
            echo

            PIDS=$(echo "$NODE_PROCESSES" | awk '{print $2}')
            for PID in $PIDS; do
              echo "Attempting to kill Node.js process with PID $PID..."
              taskkill //PID $PID //F || echo "Failed to kill PID $PID (might already be dead or inaccessible)"
            done
          else
            echo "No running Node.js process found."
          fi

      - name: Build the application
        shell: bash
        working-directory: E:/AceroApplications
        run: |
          export $(grep -v '^#' .env | xargs)
          npm run build

      - name: Start the application in the background
        shell: bash
        working-directory: E:/AceroApplications
        run: |
          export $(grep -v '^#' .env | xargs)

          echo "Starting the app in the background..."
          nohup npm run start > app.log 2>&1 &

          sleep 5

          NODE_RUNNING=$(tasklist | grep "node.exe" || true)
          if [ -n "$NODE_RUNNING" ]; then
            echo "Node.js process is running:"
            echo "$NODE_RUNNING"
          else
            echo "Failed to start Node.js application."
            tail -n 20 app.log
            exit 1
          fi

      - name: Tail application logs (Optional)
        shell: bash
        working-directory: E:/AceroApplications
        run: |
          echo "Tailing the app logs..."
          tail -n 20 app.log
