name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes from master
        run: |
          git pull origin master

      - name: Check if Node.js is installed
        shell: sh
        run: |
          if ! command -v node >/dev/null 2>&1; then
            echo "Node.js is not installed. Installing the latest version..."
            curl -fsSL https://deb.nodesource.com/setup_16.x | sh
            apt-get install -y nodejs
          else
            echo "Node.js is already installed."
          fi

      - name: Delete node_modules
        shell: sh
        run: |
          if [ -d "node_modules" ]; then
            rm -rf node_modules
          fi

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Start the application
        run: npm run start
