name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes from master
        shell: bash
        run: |
          git pull origin master

      - name: Delete node_modules
        shell: bash
        run: |
          if [ -d "node_modules" ]; then
            echo "Removing existing node_modules directory..."
            rm -rf node_modules
          else
            echo "No node_modules directory to delete."
          fi

      - name: Install dependencies
        shell: bash
        run: npm install

      - name: Check if any Node.js process is running and kill it
        shell: bash
        run: |
          echo "Looking for running node.exe processes..."
          NODE_PROCESSES=$(tasklist | grep "node.exe" || true)
      
          if [ -n "$NODE_PROCESSES" ]; then
            echo "Found Node.js process(es):"
            echo "$NODE_PROCESSES"
            echo
      
            PIDS=$(echo "$NODE_PROCESSES" | awk '{print $2}')
            for PID in $PIDS; do
              echo "Attempting to kill Node.js process with PID $PID..."
              taskkill //PID $PID //F || echo "Failed to kill PID $PID (might already be dead or inaccessible)"
            done
          else
            echo "No running Node.js process found."
          fi

      - name: Build the application
        shell: bash
        run: npm run build

      - name: Start the application
        shell: bash
        run: npm run start
